### ISSUE TITLE
Filezilla Keyfile wont download

### ISSUE THREAD

**Issue by shicks-cfs** [cfs-energy/idea#174]
When setting up filezilla to download the keyfile in step 2 of the file transfer page, the hyperlink doesn't initiate any downloads

![image](https://github.com/user-attachments/assets/a5524b32-f432-4486-85b2-ddaf1a029098)

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0021) - Video On Demand workflow with AWS Step Functions, MediaConvert, MediaPackage, S3, CloudFront and DynamoDB. Version **v5.0.0**_". If the description does not contain the version information, you can look at the mappings section of the template:

```yaml
Mappings:
  SourceCode:
    General:
      S3Bucket: "solutions"
      KeyPrefix: "scale-out-computing-on-aws/v2.0.0"
```

- [ ] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by cfsnate** [comment]
Hi @shicks-cfs

I was unable to replicate this. Oftentimes if the user is missing their `~/.ssh` folder or for some reason keys were not generated in their ~/.ssh folder, this behavior will occur. The only times I've seen this happen is when the folder was deleted by mistake.

The user should be able to regenerate their key using `ssh-keygen` from an eVDI node.
